const types = {
  OFFERS_FETCH_REQUESTED: 'OFFERS_FETCH_REQUESTED',
  OFFERS_FETCH_SUCCEEDED: 'OFFERS_FETCH_SUCCEEDED',
  OFFERS_FETCH_FAILED: 'OFFERS_FETCH_FAILED',
  SUBSCRIPTION_REQUESTED: 'SUBSCRIPTION_REQUESTED',
  SUBSCRIPTION_SUCCEEDED: 'SUBSCRIPTION_SUCCEEDED',
  SUBSCRIPTION_FAILED: 'SUBSCRIPTION_FAILED',
  SELECT_OFFER: 'SELECT_OFFER',
};

export default types;
