const types = {
  OFFERS_FETCH_REQUESTED: 'OFFERS_FETCH_REQUESTED',
  OFFERS_FETCH_SUCCEEDED: 'OFFERS_FETCH_SUCCEEDED',
  OFFERS_FETCH_FAILED: 'OFFERS_FETCH_FAILED',
  SELECT_OFFER: 'SELECT_OFFER',
};

export default types;
